In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pandas.plotting import parallel_coordinates
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import silhouette_score

plt.rcParams['figure.figsize'] = [11, 8]
RANDOM_STATE = 42

In [9]:
URL = "https://media.githubusercontent.com/media/vxuv/ratemyprofessor-dataset/main/reviews.csv"
df = pd.read_csv(URL, nrows=10000, on_bad_lines="skip")
print(df.shape)
display(df.head())

(10000, 16)

,id,first_name,last_name,title,quality,difficulty,tags,comment,date,emotional_label,class,for_credit,attendence,would_take_again,grade,textbook
0,2000000,Kimberly,Rule,Professor in the Criminal Justice department a...,5.0,5.0,['Gives good feedback'],<TEACHER>'s classes are great! I learned so mu...,"May 6th, 2021",awesome,FRSC510,True,Mandatory,True,A,True
1,2000000,Kimberly,Rule,Professor in the Criminal Justice department a...,5.0,5.0,[],She is super nice! She tends to talk to the cl...,"Apr 21st, 2015",awesome,FRSC201,True,NaN,NaN,NaN,False
2,2000000,Kimberly,Rule,Professor in the Criminal Justice department a...,5.0,5.0,[],"AKA <TEACHER> Carisi. Yes, she speaks as if i...","Apr 13th, 2015",awesome,FRSC201,True,NaN,NaN,NaN,False
3,2000002,Rusty,Spell,Professor in the English department at Alabama...,5.0,5.0,['Gives good feedback'],He was a really good professor. Always let us ...,"Jan 26th, 2022",awesome,ENG131,True,NaN,True,A,True
4,2000002,Rusty,Spell,Professor in the English department at Alabama...,4.0,4.0,['Tough grader'],"Great teacher, willing to help . All you have ...","Jan 13th, 2022",awesome,ENG131,True,NaN,True,NaN,NaN

In [10]:
print(df.columns.tolist())
print()
print(df.info())

['id', 'first_name', 'last_name', 'title', 'quality', 'difficulty', 'tags', 'comment', 'date', 'emotional_label', 'class', 'for_credit', 'attendence', 'would_take_again', 'grade', 'textbook']

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                10000 non-null  int64
 1   first_name        9988 non-null   str
 2   last_name         10000 non-null  str
 3   title             10000 non-null  str
 4   quality           10000 non-null  float64
 5   difficulty        10000 non-null  float64
 6   tags              10000 non-null  str
 7   comment           9991 non-null   str
 8   date              10000 non-null  str
 9   emotional_label   10000 non-null  str
 10  class             9991 non-null   str
 11  for_credit        9688 non-null   object
 12  attendence        7677 non-null   str
 13  would_take_again  6500 non-null   object
 14  grade             6823 non-null   str
 15  textbook          9553 non-null   object
dtypes: float64(2), int64(1), object(3), str(10)
memory usage: 1.2+ MB
None

In [14]:
df1 = df.copy()

df1 = df1[['difficulty', 'would_take_again', 'for_credit']]
print(df1.shape)
display(df1.head())

(10000, 3)

   difficulty would_take_again for_credit
0         5.0             True       True
1         5.0              NaN       True
2         5.0              NaN       True
3         5.0             True       True
4         4.0             True       True

In [ ]:
print(df1[['difficulty', 'would_take_again', 'for_credit']].isna().sum())

difficulty             0
would_take_again    3500
for_credit           312
dtype: int64

      difficulty would_take_again for_credit
0            5.0             True       True
1            5.0              NaN       True
2            5.0              NaN       True
3            5.0             True       True
4            4.0             True       True
...          ...              ...        ...
9995         4.0             True       True
9996         4.0             True       True
9997         4.0             True       True
9998         2.0            False       True
9999         4.0             True       True

[10000 rows x 3 columns]