In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
file_path = 'ПЗ1.Метрики.xlsx'

df_reg = pd.read_excel(file_path, sheet_name='Regression')
df_bin = pd.read_excel(file_path, sheet_name='Binary Classification')
df_reg

                model   part  Y_true  Y_pred
0     Polynominal Reg   test     597     585
1              LinReg   test    1814    1845
2              LinReg   test    1339    1375
3              LinReg   test     673     690
4              LinReg   test    1912    1952
...               ...    ...     ...     ...
5195  Polynominal Reg  train    1380    1418
5196           LinReg   test    1401    1403
5197           LinReg  train    1072    1098
5198           LinReg  train    1464    1481
5199  Polynominal Reg   test    1108    1132

[5200 rows x 4 columns]

In [3]:
def reg_metrics(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    return {
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse,
        "R2": r2
    }

reg_rows = []
for (model, part), group in df_reg.groupby(["model", "part"]):
    result = reg_metrics(group["Y_true"].values, group["Y_pred"].values)

    result["model"] = model
    result["part"] = part

    reg_rows.append(result)

print(result)
reg_result = pd.DataFrame(reg_rows)[['model', 'part', 'MAE', 'MSE', 'RMSE', 'R2']]
reg_result = reg_result.sort_values(["model", "part"]).reset_index(drop=True)
reg_result

{'MAE': 17.037965072133638, 'MSE': 417.08959757023536, 'RMSE': np.float64(20.422771544779014), 'R2': 0.9982339671862505, 'model': 'Polynominal Reg', 'part': 'train'}

             model   part        MAE         MSE       RMSE        R2
0           LinReg   test  16.992492  416.427928  20.406566  0.998268
1           LinReg  train  16.825080  405.358626  20.133520  0.998381
2  Polynominal Reg   test  16.561971  402.962279  20.073920  0.998319
3  Polynominal Reg  train  17.037965  417.089598  20.422772  0.998234

In [4]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

In [5]:
def bin_metrics(y_true, y_pred, y_proba):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1-score": f1_score(y_true, y_pred, zero_division=0),
        "AUC ROC": roc_auc_score(y_true, y_proba),
        "AUC PR": average_precision_score(y_true, y_proba)
    }

bin_rows = []
bin_curves = {}
cm_dict = {}

for (model, part), group in df_bin.groupby(["model", "part"]):
    y_true = group["Y_true"].values
    y_pred = group["Y_pred"].values
    y_proba = group["Y_pred_proba_1"].values

    m = bin_metrics(y_true, y_pred, y_proba)
    m["model"] = model
    m["part"] = part
    bin_rows.append(m)
    # print(bin_rows)

bin_results = pd.DataFrame(bin_rows)[
    ["model", "part", "Accuracy", "Precision", "Recall", "F1-score", "AUC ROC", "AUC PR"]
].sort_values(["model", "part"]).reset_index(drop=True)

bin_results

,model,part,Accuracy,Precision,Recall,F1-score,AUC ROC,AUC PR
0,DecisionTree,test,0.515085,0.534682,0.523338,0.528949,0.516775,0.534249
1,DecisionTree,train,0.495686,0.508661,0.493884,0.501164,0.483232,0.494351
2,GradientBoosting,test,0.471538,0.477658,0.471125,0.474369,0.472651,0.487862
3,GradientBoosting,train,0.498420,0.526490,0.476762,0.500393,0.510820,0.543110